### ISSUE TITLE
Array names

### ISSUE THREAD

**Issue by bpraveenaero** [ADACFD/CFD#2]
Can we maintain a list of important array list names and the contents of its each column? It will be much easier for recollection at any time.

**Comment by aeroiitkgp** [comment]
Doxygen document is best to keep track of arrays functions, variables, etc. It creates a document with links and description. I will try to learn about it.

**Comment by aeroiitkgp** [comment]
Implemented Doxygen for documentation. We will comment every class, function and variables in order to keep everything well documented.
